<?php

namespace PlatBundle\Repository;

/**
 * HumeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HumeurRepository extends \Doctrine\ORM\EntityRepository
{
}
