<?php

namespace PlatBundle\Repository;

/**
 * UstensilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UstensilesRepository extends \Doctrine\ORM\EntityRepository
{
    public function ustensilesAlphabeticalOrder(){
        $query = $this->createQueryBuilder('u')
            ->orderBy('u.nom', 'ASC');
        return $query;
    }
    public function ustensilesAlphabeticalOrderForDisplay(){
        $query = $this->createQueryBuilder('u')
            ->orderBy('u.nom', 'ASC');
        return $query->getQuery()->getResult();
    }
}
