plat_plat:
    resource: "@PlatBundle/Resources/config/routing/plat.yml"
    prefix:   /

plat_typeplat:
    resource: "@PlatBundle/Resources/config/routing/typeplat.yml"
    prefix:   /typeplat

plat_note:
    resource: "@PlatBundle/Resources/config/routing/note.yml"
    prefix:   /note

plat_specialite:
    resource: "@PlatBundle/Resources/config/routing/specialite.yml"
    prefix:   /specialite

plat_ustensiles:
     resource: "@PlatBundle/Resources/config/routing/ustensiles.yml"
     prefix:   /ustensiles

plat_homepage:
    path:     /testplat
    defaults: { _controller: PlatBundle:Default:index }

test:
    path:     /test
    defaults: { _controller: PlatBundle:Plat:test }
plat_get:
    path:     /get/{id}
    defaults: { _controller: PlatBundle:Plat:getPlat }
after_request:
    path:     /afterRequest
    defaults: { _controller: PlatBundle:Plat:afterRequest }
plat_rec:
    path:     /VosPlatsRecommande
    defaults: { _controller: PlatBundle:Plat:platsRec }
    methods: [GET]
form_plats_rec:
    path:     /RemplirFormulaire
    defaults: { _controller: PlatBundle:Plat:showFormulaire }

rechercheSimple:
    path:     /recherche
    defaults: { _controller: PlatBundle:Plat:rechSimple }