login:
  path:     /login
  defaults: { _controller: UserBundle:Security:login }

register:
  path:     /register/
  defaults: { _controller: UserBundle:Registration:register }

profile_edit:
  path:     /profile/edit
  defaults: { _controller: UserBundle:Profile:edit }

