<?php

namespace MaladieBundle\Repository;

/**
 * MaladieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaladieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAlergies(){
        $query = $this->createQueryBuilder('m')
            ->where('m.type = alergie');
        return $query;
    }
    public function getMaladies(){
        $query = $this->createQueryBuilder('m')
            ->where('m.type = maladie');
        return $query;
    }
}
